### ISSUE TITLE
Allow the possibility to disable Emote Mouse Highlight

### ISSUE THREAD

**Issue by JoachimFlottorp** [SevenTV/SevenTV#18]
Settings to disable the Emote Highlight when you mouse over. The 7TV highlight disables the possibility to further open the emote owners channel.

![image](https://user-images.githubusercontent.com/24413121/119815797-3a069000-beec-11eb-928c-27cfaf7b5498.png)

**Comment by M-TGH** [comment]
This would be incredibly useful, as the on click menu Twitch provides also has info about the emote, e.g. whether it's a bit emote, subscriber emote (if so, what tier), etc.

Could also possibly add this kind of info into the Emote Highlight, or allowing the native on-click functionality from Twitch to keep functioning whilst this feature is on would work just as well I'd think, as long as those don't conflict. Although that might warrant a separate issue since this one is (at least titled to be) mainly about adding a toggle for the feature. 
So, let me know if you want me to make a separate issue to fix/adjust the feature in one of those ways which would fix this as well.

**Comment by AnatoleAM** [comment]
This will be added as part of version 2.1.2 per #194
