### ISSUE TITLE
[Bug] Available Emote Slots Won't Fill

### ISSUE THREAD

**Issue by imlightbringer** [SevenTV/SevenTV#213]
**Describe the bug**
Specific channel I am an editor of shows 248/250 emote slots available but won't let me fill the last 2 available slots. 7TV acts as though there isn't enough space even though there are 2 emote slots left.

**To Reproduce**
1. Go to 7TV website and activate editor mode
2. Click on any emote on 7TV to add to that channel
3. See error showing 250 slots are full
3. Navigate to the 7TV channel page being edited
4. See 2 slots are available

**Expected behavior**
Allow me to add emotes to the channel I edit for that has 2 remaining slots.

**Screenshots**
<img width="506" alt="Screen Shot 2022-01-27 at 8 16 33 PM" src="https://user-images.githubusercontent.com/98565126/151470094-d17cfcee-98ec-48d6-8bcd-121cc6dd8ca3.png">

<img width="385" alt="Screen Shot 2022-01-27 at 8 17 15 PM" src="https://user-images.githubusercontent.com/98565126/151470109-316242a4-3590-4646-b7dd-78600b4e8118.png">

**Version:**
Version: 2.1.4
Server: //api.7tv.app
Browser: Chrome

**Comment by Excellify** [comment]
I assume the channel you manage was a subscriber previously. The zero-width emotes they had enabled are now disabled, but still bound to the account. This is so that if they resubscribe they become enabled again. The website should display this better, but it will probably not be fixed untill the next version of the website is released. 

These are the two zero-width emotes that make it seem like you have two more slots: 
- https://7tv.app/emotes/61159e9903dae26bc706eaa6
- https://7tv.app/emotes/61e62b39095be332e347deaa

You can either get the channel owner to resubscribe (or gift) or disable the emotes. 
One of them is a global emote so it should be disabled either way as it can be used regardless. 

This issue should be directed to the [SevenTV/App](https://github.com/SevenTV/App) repository for future reference.
