### ISSUE TITLE
[Enhancement Request] - Remove Mod Actions from Non-Moderators

### ISSUE THREAD

**Issue by fouram** [SevenTV/SevenTV#214]
**Describe the feature**
Removal of the ability for non-mods to see moderator actions in a channel. OR allow channels to disable it's use somehow.

**Expected behavior**
Chatters will stop questioning when mods are banning new ban-evader's accounts, arguing with timeouts, calling a streamer out for a timeout vs ban, etc. There is a reason Twitch hid those messages from the plebs and it's so they don't start petty fights over it.

**Comment by AnatoleAM** [comment]
> Chatters will stop questioning when mods are banning new ban-evader's accounts
That wouldn't be the case, because chat clients like Chatterino also allow anyone to see this information. It's sent by Twitch mostly as an instruction that clients should delete a user's messages, which makes this public information.

Other browser extensions display this information too, it's pretty common across the board and there is no way to prevent "the plebs" from seeing this. 

The one thing I've been considering though is to make this option OFF by default, as I don't actually remember why it was set to default-on, likely more of an oversight.

**Comment by fouram** [comment]
This is good information, and an angle I had not considered. It would be nice for this information to be off by default, however.
