### ISSUE TITLE
Extension does not work with the chat from Alternative Player for Twitch

### ISSUE THREAD

**Issue by Lareyt** [SevenTV/SevenTV#71]
This extension doesn't work with the Alternative Player for Twitch extension. The same chat window loads in that extension, but 7TV doesn't appear there and none of the emotes from it work. BBTV emotes and features are working though. Is it possible to have a working integration or should this be raised with the Alternative Player for Twitch developer?

**Comment by AnatoleAM** [comment]
Will look at a way to do this

**Comment by AnatoleAM** [comment]
Likely impossible. Alternate Player runs in its own extension context ,which is inaccessible by any other extension. As for how BTTV and FFZ work there I'm not sure, perhaps the author of the Alternate Player extension added support himself. You'd need to ask him to support 7TV.

If someone knows a way around it this issue can be re-opened.

**Comment by Lareyt** [comment]
Thanks for looking into it, will reach out to the Alternative Player for Twitch developer.

**Comment by robmonte** [comment]
Yes, from previous investigations of my own, I had learned that the author of the Alternate Twitch Player extension built FFZ/BTTV support into his addon. 

WORKAROUND:
However, since FFZ has a plugin to load 7TV within in itself, you can disable the dedicated 7TV addon, enable the 7TV-FFZ plugin, then turn the dedicated 7TV emote back on. This will let Alternate Twitch Player pages load 7TV through FFZ.
